
const VIDEO_STATUS_PREFIX = 'VIDEO_STATUS'

export const VIDEO_STATUS = {
  ERROR: `${VIDEO_STATUS_PREFIX}:ERROR`,
  PLAYING: `${VIDEO_STATUS_PREFIX}:PLAYING`,
  LOADING: `${VIDEO_STATUS_PREFIX}:LOADING`
}
